services:
  database:
    container_name: npp-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
     # /var/lib/postgresql/data
    networks:
      - npp-iot-network

  node-red:
    container_name: npp-nodered
    build:
      context: ./node-red
      dockerfile: Dockerfile
    image: npp-iot/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
    networks:
      - npp-iot-network

  mosquitto:
    container_name: npp-mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data/:/mosquitto/data
    networks:
      - npp-iot-network

  influxdb:
    container_name: npp-influxdb
    image: influxdb:2.8.0
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=npp
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=49s_MTlVPDvDs58kjmXT_GMNI3gB2AzfQ-__AmynELGapRUG0SpPM0NPdRcg9V-tyj3n--W5_nGSMVygL_ZaZA==
    networks:
      - npp-iot-network

  grafana:
    container_name: npp-grafana
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - npp-iot-network

networks:
  npp-iot-network:
    driver: bridge